### ISSUE TITLE
Permission Needed

### ISSUE THREAD

**Issue by ZLT-ops** [Seeps/VRAutomate#1]
Hi Seeps,

Could you comment on what the IAM permission that is needed to invoke the script?

**Comment by Seeps** [comment]
@ZLT-ops Sorry for the late reply!

I made this while having full AWS permissions (admin), however you should be able to get this running easily with `AmazonEC2FullAccess` as it's primarily using EC2. For something more specific, you can try:

`ec2:DescribeInstances`
`ec2:DescribeSecurityGroups`
`ec2:DescribeImages`
`ec2:DescribeKeyPairs`
`ec2:CreateSecurityGroup`
`ec2:CreateTags`
`ec2:CreateKeyPair`
`ec2:CreateSecurityGroupRule`
`ec2:RunInstances`
`ec2:TerminateInstances`
`ec2:DeleteSecurityGroup`
`ec2:DeleteKeyPair`

In the **main.tf** file there are lines commented with **##REVIEW** which you may want to change. The region and AMI ID are two you will need to check depending on the region and Linux distribution you wish to use. Aside from that, you will also want to update the Velociraptor binary URLs (Windows/Linux) in the **velociraptor.yml** file.

As you can tell, this is quite an old version I had made and am currently in the process of updating with a new one that is WAY more refined and easier to use. I can let you know when that one comes out :)

**Comment by ZLT-ops** [comment]
Thanks for providing the information
Created a pull request to fix both issues
